import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ParticleColorProvider } from "@/contexts/ParticleColorContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: '#000000', overflow: 'hidden' }}>
      <body
        style={{ backgroundColor: '#000000', color: '#ffffff', overflow: 'hidden' }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ParticleColorProvider>
          {children}
        </ParticleColorProvider>
      </body>
    </html>
  );
}
